version: "3"

services:
  postgres:
    image: postgres:14.3
    volumes:
      - ./data/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=workshop